src/Entity/Commande.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Gedmo\Mapping\Annotation as Gedmo;
use App\Repository\CommandeRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommandeRepository::class)]
class Commande
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 50)]
    private $prenom;

    #[ORM\Column(type: 'string', length: 50)]
    private $nom;

    #[ORM\Column(type: 'string', length: 255)]
    private $adresse_livraison;

    #[ORM\Column(type: 'integer')]
    private $code_postal;

    #[ORM\Column(type: 'string', length: 100)]
    private $ville;

    #[ORM\Column(type: 'string', length: 50)]
    private $pays;

    #[ORM\Column(type: 'string', length: 10)]
    private $telephone;

     /**
     * @Gedmo\Timestampable(on="create")
     */
    #[ORM\Column(type: 'datetime')]
    private $date_commande;

    #[ORM\ManyToOne(targetEntity: Utilisateur::class, inversedBy: 'commandes')]
    #[ORM\JoinColumn(nullable: false)]
    private $utilisateur;

    #[ORM\OneToMany(mappedBy: 'commande', targetEntity: LigneCommande::class)]
    private $ligneCommandes;

    public function __construct()
    {
        $this->ligneCommandes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getAdresseLivraison(): ?string
    {
        return $this->adresse_livraison;
    }

    public function setAdresseLivraison(string $adresse_livraison): self
    {
        $this->adresse_livraison = $adresse_livraison;

        return $this;
    }

    public function getCodePostal(): ?int
    {
        return $this->code_postal;
    }

    public function setCodePostal(int $code_postal): self
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getPays(): ?string
    {
        return $this->pays;
    }

    public function setPays(string $pays): self
    {
        $this->pays = $pays;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getDateCommande(): ?\DateTimeInterface
    {
        return $this->date_commande;
    }

    // public function setDateCommande(\DateTimeInterface $date_commande): self
    // {
    //     $this->date_commande = $date_commande;

    //     return $this;
    // }

    public function getUtilisateur(): ?Utilisateur
    {
        return $this->utilisateur;
    }

    public function setUtilisateur(?Utilisateur $utilisateur): self
    {
        $this->utilisateur = $utilisateur;

        return $this;
    }

    /**
     * @return Collection<int, LigneCommande>
     */
    public function getLigneCommandes(): Collection
    {
        return $this->ligneCommandes;
    }

    public function addLigneCommande(LigneCommande $ligneCommande): self
    {
        if (!$this->ligneCommandes->contains($ligneCommande)) {
            $this->ligneCommandes[] = $ligneCommande;
            $ligneCommande->setCommande($this);
        }

        return $this;
    }

    public function removeLigneCommande(LigneCommande $ligneCommande): self
    {
        if ($this->ligneCommandes->removeElement($ligneCommande)) {
            // set the owning side to null (unless already changed)
            if ($ligneCommande->getCommande() === $this) {
                $ligneCommande->setCommande(null);
            }
        }

        return $this;
    }

}

src/Entity/Vente.php
<?php

namespace App\Entity;

use Gedmo\Mapping\Annotation as Gedmo;
use App\Repository\VenteRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: VenteRepository::class)]
class Vente
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'float')]
    private $prix;

     /**
     * @Gedmo\Timestampable(on="create")
     */
    #[ORM\Column(type: 'datetime')]
    private $date_vente;

    #[ORM\ManyToOne(targetEntity: Utilisateur::class, inversedBy: 'ventes')]
    #[ORM\JoinColumn(nullable: false)]
    private $utilisateur;

    #[ORM\ManyToOne(targetEntity: Produit::class, inversedBy: 'ventes')]
    private $produit;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getDateVente(): ?\DateTimeInterface
    {
        return $this->date_vente;
    }

    // public function setDateVente(\DateTimeInterface $date_vente): self
    // {
    //     $this->date_vente = $date_vente;

    //     return $this;
    // }

    public function getUtilisateur(): ?Utilisateur
    {
        return $this->utilisateur;
    }

    public function setUtilisateur(?Utilisateur $utilisateur): self
    {
        $this->utilisateur = $utilisateur;

        return $this;
    }

    public function getProduit(): ?Produit
    {
        return $this->produit;
    }

    public function setProduit(?Produit $produit): self
    {
        $this->produit = $produit;

        return $this;
    }
}

src/Controller/CompteController.php
<?php

namespace App\Controller;

use App\Entity\Sujet;
use App\Entity\Vente;
use App\Entity\Recette;
use App\Form\VenteType;
use App\Entity\Commande;
use App\Entity\Commentaire;
use App\Repository\SujetRepository;
use App\Repository\VenteRepository;
use App\Repository\RecetteRepository;
use App\Repository\CommandeRepository;
use App\Repository\CommentaireRepository;
use Doctrine\Persistence\ManagerRegistry;
use App\Repository\LigneCommandeRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/compte', name: 'app_compte_')]
class CompteController extends AbstractController
{
    #[Route('/recette', name: 'recette')]
    public function recette(RecetteRepository $recetteRepository): Response
    {
        $utilisateur = $this->getUser('user');
        $recettes = $recetteRepository->mesrecettes($utilisateur);
        return $this->render('compte/recette.html.twig', [
            'recettes' => $recettes,
        ]);
    }

    #[Route('/sujet', name: 'sujet')]
    public function sujet(SujetRepository $sujetRepository): Response
    {
        $utilisateur = $this->getUser('user');
        $sujets = $sujetRepository->messujets($utilisateur);
        return $this->render('compte/sujet.html.twig', [
            'sujets' => $sujets,
        ]);
    }

    #[Route('/commentaire', name: 'commentaire')]
    public function commentaire(CommentaireRepository $commentaireRepository): Response
    {
        $utilisateur = $this->getUser('user');
        $commentaires = $commentaireRepository->mescommentairesrecette($utilisateur);
        $commentaires2 = $commentaireRepository->mescommentairessujet($utilisateur);
        return $this->render('compte/commentaire.html.twig', [
            'commentaires' => $commentaires,
            'commentaires2' => $commentaires2,
        ]);
    }

    #[Route('/annonce', name: 'annonce')]
    public function annonce(VenteRepository $venteRepository): Response
    {
        $utilisateur = $this->getUser('user');
        $ventes = $venteRepository->mesventes($utilisateur);
        return $this->render('compte/annonce.html.twig', [
            'ventes' => $ventes,
        ]);
    }

    #[Route('/commande', name: 'commande')]
    public function commande(CommandeRepository $commandeRepository): Response
    {
        $utilisateur = $this->getUser('user');
        $commande = $commandeRepository->mescommandes($utilisateur);
        return $this->render('compte/commande.html.twig', [
            'commande' => $commande,
        ]);
    }

    #[Route('/commentaire/delete/{id}', name: 'commentaire_delete')]
    public function deletecommentaire(Commentaire $commentaire, ManagerRegistry $doctrine): Response
    {
        $em = $doctrine->getManager();
        $em->remove($commentaire);
        $em->flush();
        $this->addFlash('success', 'Commentaire supprimé !');
        return $this->redirectToRoute('app_compte_commentaire');
    }

    #[Route('/sujet/delete/{id}', name: 'sujet_delete')]
    public function deletesujet(Sujet $sujet, ManagerRegistry $doctrine): Response
    {
        $em = $doctrine->getManager();
        $em->remove($sujet);
        $em->flush();
        $this->addFlash('success', 'Sujet supprimé !');
        return $this->redirectToRoute('app_compte_sujet');
    }

    #[Route('/recette/delete/{id}', name: 'recette_delete')]
    public function deleterecette(Recette $recette, ManagerRegistry $doctrine): Response
    {
        $em = $doctrine->getManager();
        $em->remove($recette);
        $em->flush();
        $this->addFlash('success', 'Recette supprimée !');
        return $this->redirectToRoute('app_compte_recette');
    }

    #[Route('/annonce/delete/{id}', name: 'annonce_delete')]
    public function deleteannonce(Vente $vente, ManagerRegistry $doctrine): Response
    {
        $em = $doctrine->getManager();
        $em->remove($vente);
        $em->flush();
        $this->addFlash('success', 'Annonce supprimée !');
        return $this->redirectToRoute('app_compte_annonce');
    }

    #[Route('/annonce/update/{id}', name: 'annonce_update')]
    public function updateannonce(Vente $vente, Request $request, ManagerRegistry $doctrine): Response
    {
        $form = $this->createForm(VenteType::class, $vente);
        
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $em = $doctrine->getManager();
            $em->flush();
            return $this->redirectToRoute('app_compte_annonce');
        }
        return $this->render('annonce/add.html.twig', [
            'form' => $form->createView(),
        ]);    }

    
}

templates/compte/annonce.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Mes annonces{% endblock %}

{% block body %}
{% if ventes %}
    <div id="card">
        {% for vente in ventes %}
        
                <div class="card m-3" style="width: 15rem; ">
                    <img src="{{ vente.produit.image }}" class="card-img-top" alt="" style="width: 100%">
                    <div class="card-body">
                    <h5 class="card-title fw-bolder">{{ vente.produit.nom}}</h5>
                    <h5 class="card-title fw-bolder">Prix : {{ vente.prix}} €</h5> 
                    </div>
                    <ul class="list-group list-group-flush">
                    <li class="list-group-item">Posté le {{vente.dateVente | format_datetime( locale='fr',pattern="dd MMMM YYYY") }}</li>
                    </ul> 
                    {% if is_granted("ROLE_FRUITICULTEUR") and vente.utilisateur.id == app.user.id %}
                    <a href="{{ path('app_compte_annonce_update', {id: vente.id}) }}" class="btn btn-info btn-sm">Modifier</a>
                    <a href="{{ path('app_compte_annonce_delete', {id: vente.id}) }}" class="btn btn-danger btn-sm" onclick="return confirm('Suppression ?')">Supprimer</a>
                    {% endif %}
                </div> 
        
        {% endfor %}
    </div>
{% else %}
    <p style="text-align: center; color: white;">Vous n'avez pas posté d'annonces</p>
{% endif %}
{% endblock %}

templates/compte/commande.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Mes commandes{% endblock %}

{% block body %}
<style>
    tr{
        border: 1px solid black;
    }
    td{
        font-weight: bold;
        text-align: center;
        color: white;
    }
    tr{
        margin: 10px;
    }
    button{
        border-radius: 5px;
        background-color: rgb(8, 98, 162);
        color: white;
    }
</style>
{% if commande %}
    <table>
        <thead>
            <th>Nom</th>
            <th>Prenom</th>
            <th>Adresse</th>
            <th>Date</th>
            <th>Action</th>
        
        </thead>
        {% for commande in app.user.commandes | reverse %}
        <tr>
            <td> {{commande.nom}} </td>
            <td> {{commande.prenom}} </td>
            <td> {{commande.adresseLivraison}} </td>
            <td> {{commande.dateCommande | format_datetime( locale='fr',pattern="dd MMMM YYYY HH:mm")}} </td>
            <td>
                <a href="{{ path('app_commande_view', {id: commande.id}) }}">
                    <button>Détails</button>
                </a>
            </td> 
        </tr>
        {% endfor %}
    </table>
{% else %}
    <p style="text-align: center; color: white;">Vous n'avez pas passé de commandes</p>
{% endif %}

{% endblock %}

templates/compte/commentaire.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Mes commentaires{% endblock %}

{% block body %}

{% if commentaires or commentaires2 %}
    <div id="table">
        <table>
            <thead>
                <tr>
                    <th>Mes commentaires de recettes</th>
                    <th>Mes commentaires de sujets</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td id="td1">
                        {% for commentaire in commentaires %}
                        <div id="comms2">
                            <div id="comms">
                                <p>{{commentaire.contenu}}</p>
                                <p id="datecomms">Le {{commentaire.DateCommentaire | format_datetime( locale='fr',pattern="dd MMMM YYYY HH:mm")}}</p>
                                <a href="{{ path('app_compte_commentaire_delete', {id: commentaire.id}) }}" class="btn btn-danger btn-sm" onclick="return confirm('Suppression ?')">Supprimer</a>
                            </div>
                        </div>
                        {% endfor %}
                    </td>
                    <td id="td2">
                        {% for commentaire in commentaires2 %}
                        <div id="comms2">
                            <div id="comms">
                                <p>{{commentaire.contenu}}</p>
                                <p id="datecomms">Le {{commentaire.DateCommentaire | format_datetime( locale='fr',pattern="dd MMMM YYYY HH:mm")}}</p>
                                <a href="{{ path('app_compte_commentaire_delete', {id: commentaire.id}) }}" class="btn btn-danger btn-sm" onclick="return confirm('Suppression ?')">Supprimer</a>
                            </div>
                        </div>
                        {% endfor %}
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
{% else %}
    <p style="text-align: center; color: white;">Vous n'avez pas posté de commentaires</p>
{% endif %}
{% endblock %}

templates/compte/recette.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Mes recettes{% endblock %}

{% block body %}
{% if recettes %}
    <div id="card">
        {% for recette in recettes %}
        
            <a href="{{ path('app_recette_view', {slug: recette.slug}) }}" class="card-link">
                <div class="card m-3 d-flex justify-content-between" style="width: 15rem; ">
                    <img src="{{ recette.image }}" class="card-img-top" alt="" style="width: 100%">
                    <div class="card-body">
                    <h5 class="card-title fw-bolder">{{ recette.titre}}</h5>
                    <p class="card-text">{{ recette.instruction | u.truncate(100, '...')  | raw}}</p>
                    </div>
            </a>
                    <ul class="list-group list-group-flush">
                    <li class="list-group-item">{{recette.DatePublication | format_datetime( locale='fr',pattern="dd MMMM YYYY HH:mm") }}</li>
                    </ul>
                    <a href="{{ path('app_compte_recette_delete', {id: recette.id}) }}" class="btn btn-danger btn-sm" onclick="return confirm('Suppression ?')">Supprimer</a>
                </div>
        
        {% endfor %}
    </div>
{% else %}
    <p style="text-align: center; color: white;">Vous n'avez pas posté de recettes</p>
{% endif %}
{% endblock %}

templates/compte/sujet.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Mes sujets{% endblock %}
{% block body %}
{% if sujets %}

{% for sujet in sujets %}
    <div id="card2">
        <div id="souscard">
            <a href="{{ path('app_sujet_view', {slug: sujet.slug}) }}" class="card-link">
                <div class="card"  style="margin:20px;">
                    <div class="card-body">
                        <h1>{{sujet.titre}}</h1>
                        <div>{{sujet.contenu | u.truncate(200, '...')  | raw}}</div>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">{{sujet.DatePublication | format_datetime( locale='fr',pattern="dd MMMM YYYY HH:mm") }}</li>
                        </ul>
                        <a href="{{ path('app_compte_sujet_delete', {id: sujet.id}) }}" class="btn btn-danger btn-sm" onclick="return confirm('Suppression ?')">Supprimer</a>
                    </div>
                </div>
            </a>
        </div>
    </div>
{% endfor %}
{% else %}
    <p style="text-align: center; color: white;">Vous n'avez pas posté de sujets</p>
{% endif %}

{% endblock %}