src/Entity/Commande.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Gedmo\Mapping\Annotation as Gedmo;
use App\Repository\CommandeRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommandeRepository::class)]
class Commande
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 50)]
    private $prenom;

    #[ORM\Column(type: 'string', length: 50)]
    private $nom;

    #[ORM\Column(type: 'string', length: 255)]
    private $adresse_livraison;

    #[ORM\Column(type: 'integer')]
    private $code_postal;

    #[ORM\Column(type: 'string', length: 100)]
    private $ville;

    #[ORM\Column(type: 'string', length: 50)]
    private $pays;

    #[ORM\Column(type: 'string', length: 10)]
    private $telephone;

     /**
     * @Gedmo\Timestampable(on="create")
     */
    #[ORM\Column(type: 'datetime')]
    private $date_commande;

    #[ORM\ManyToOne(targetEntity: Utilisateur::class, inversedBy: 'commandes')]
    #[ORM\JoinColumn(nullable: false)]
    private $utilisateur;

    #[ORM\OneToMany(mappedBy: 'commande', targetEntity: LigneCommande::class)]
    private $ligneCommandes;

    public function __construct()
    {
        $this->ligneCommandes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getAdresseLivraison(): ?string
    {
        return $this->adresse_livraison;
    }

    public function setAdresseLivraison(string $adresse_livraison): self
    {
        $this->adresse_livraison = $adresse_livraison;

        return $this;
    }

    public function getCodePostal(): ?int
    {
        return $this->code_postal;
    }

    public function setCodePostal(int $code_postal): self
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getPays(): ?string
    {
        return $this->pays;
    }

    public function setPays(string $pays): self
    {
        $this->pays = $pays;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getDateCommande(): ?\DateTimeInterface
    {
        return $this->date_commande;
    }

    // public function setDateCommande(\DateTimeInterface $date_commande): self
    // {
    //     $this->date_commande = $date_commande;

    //     return $this;
    // }

    public function getUtilisateur(): ?Utilisateur
    {
        return $this->utilisateur;
    }

    public function setUtilisateur(?Utilisateur $utilisateur): self
    {
        $this->utilisateur = $utilisateur;

        return $this;
    }

    /**
     * @return Collection<int, LigneCommande>
     */
    public function getLigneCommandes(): Collection
    {
        return $this->ligneCommandes;
    }

    public function addLigneCommande(LigneCommande $ligneCommande): self
    {
        if (!$this->ligneCommandes->contains($ligneCommande)) {
            $this->ligneCommandes[] = $ligneCommande;
            $ligneCommande->setCommande($this);
        }

        return $this;
    }

    public function removeLigneCommande(LigneCommande $ligneCommande): self
    {
        if ($this->ligneCommandes->removeElement($ligneCommande)) {
            // set the owning side to null (unless already changed)
            if ($ligneCommande->getCommande() === $this) {
                $ligneCommande->setCommande(null);
            }
        }

        return $this;
    }

}

src/Form/CommandeType.php
<?php

namespace App\Form;

use App\Entity\Commande;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CommandeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('prenom')
            ->add('nom')
            ->add('adresse_livraison')
            ->add('code_postal')
            ->add('ville')
            ->add('pays')
            ->add('telephone')
            //->add('date_commande')
            //->add('utilisateur')
            ->add('submit', SubmitType::class,[
                'label' => 'Valider'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Commande::class,
        ]);
    }
}

src/Controller/CommandeController.php
<?php

namespace App\Controller;

use App\Entity\Commande;
use App\Form\CommandeType;
use App\Entity\LigneCommande;
use App\Repository\VenteRepository;
use Symfony\Component\Mime\Address;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bridge\Twig\Mime\TemplatedEmail;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class CommandeController extends AbstractController
{
    #[Route('/commande', name: 'app_commande')]
    public function index(Request $request, ManagerRegistry $doctrine, SessionInterface $session, VenteRepository $venteRepository, MailerInterface $mailer): Response
    {
        $commande = new Commande();
        $form = $this->createForm(CommandeType::class, $commande);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $commande->setUtilisateur($this->getUser());
            $em = $doctrine->getManager();
            $em->persist($commande);
            
            $panier = $session->get('panier', []);
            $dataPanier = [];
            $total = 0;

            foreach($panier as $id => $quantite){
                $vente = $venteRepository->find($id);
                $dataPanier[] = [
                    "vente" => $vente,
                    "quantite" => $quantite,
                    "prix" => $vente->getPrix(),
                    "produit" => $vente->getProduit(),
                ];
                $total += $vente->getPrix() * $quantite;
                $lignecommande = new LigneCommande();
                $lignecommande->setPrix($vente->getPrix());
                $lignecommande->setQuantite($quantite);
                $lignecommande->setCommande($commande);
                $lignecommande->setProduit($vente->getProduit());
                $em->persist($lignecommande);
            }
            $em->flush();
            
            $email = (new TemplatedEmail())
            ->from(new Address('rougedelices@gmail.com', 'Rouge Délice'))
            ->bcc($commande->getUtilisateur()->getEmail(), $vente->getUtilisateur()->getEmail())
            ->subject('Votre commande')
            ->htmlTemplate('commande/detail_commande.html.twig')
            ->context([
                'dataPanier' => $dataPanier,
                'commande' => $commande,
                'total' => $total,
            ])
            ;
            $mailer->send($email);


            $session->remove("panier");
            $this->addFlash('successpanier', 'Votre commande a bien été enregistrée, vous allez recevoir un email avec le détail de votre commande. Pensez à vérifier dans vos spams');
            return $this->redirectToRoute('home');
        }

        return $this->render('commande/index.html.twig', [
            'form' => $form->createView(),
        ]);
    }


    #[Route('/commande/{id}', name: 'app_commande_view')]
    public function commandeid(Commande $commande): Response
    {

        return $this->render('commande/view.html.twig', [
            'commande' => $commande
        ]);
    }

}

templates/commande/detail_commande.html.twig
<div style="background-color: rgba(184, 184, 184, 0.507); padding-top: 20px; padding-bottom: 20px;">

    <div style="background-color: white; width: 80%; margin: auto;">
        <h1 style="text-align: center;">Confirmation de commande</h1>
        <div style="margin: 20px; font-size: 1.3em;">
            <p>Cher {{commande.prenom}} {{commande.nom}} ,</p>
            <p>Rouge Délice vous remercie de votre commande et de votre confiance</p>
            Nous traitons actuellement votre commande. Pour cette raison, celle-ci ne peut plus être modifiée.<br>
            Veuillez trouver ci-dessous le détail des articles commandés. <br>
            <p>Nous espérons que vous serez satisfait de vos achats.</p>
            Cordialement, <br>
            Votre équipe Rouge Délice</p>
        </div>
    
    </div>

    <div style="background-color: white; width: 80%; margin: auto;">
        <h2 style="margin: 10px;">Détails de votre commande :</h2>
        <div style="margin: 20px; font-size: 1.3em;">
            <p style="text-decoration:underline; font-weight: bold;">Adresse de livraison :</p>
            {{commande.prenom}} {{commande.nom}} <br>
            {{commande.adresseLivraison}} <br>
            {{commande.codePostal}} {{commande.ville}} <br>
            {{commande.pays}} <br>
            {{commande.telephone}}
            
            <p style="text-decoration:underline; font-weight: bold;">Date de commande :</p>
            {{commande.dateCommande | format_datetime( locale='fr',pattern="dd MMMM YYYY HH:mm")}}
        </div>
    </div>

    <div style="background-color: white; width: 80%; margin: auto;">
        <h2 style="margin: 10px;">COMMANDE :</h2>
        <table class="bg_white" role="presentation" border="0" cellpadding="0" cellspacing="0" width="100%">
            <tr>
                <th width="80%" style="text-align:left; padding: 0 2.5em; color: #000; padding-bottom: 20px">Produit:</th>
                <th width="20%" style="text-align:right; padding: 0 2.5em; color: #000; padding-bottom: 20px">Prix:</th>
                
            </tr>
            {% for panier in dataPanier %}
                <tr>
                    <td width="80%" style="text-align:left; padding: 0 2.5em; color: #000; padding-bottom: 20px; border-top: 1px solid rgb(122, 122, 122);">
                        {{panier.produit}}
                    </td>

                    <td width="20%" style="text-align:right; padding: 0 2.5em; color: #000; padding-bottom: 20px; border-top: 1px solid rgb(122, 122, 122);">
                        {{panier.prix * panier.quantite}}€
                    </td>

                </tr>
                
                <tr>
                    <td width="80%" style="text-align:left; padding: 0 2.5em; color: #000; padding-bottom: 20px">
                        Quantité: {{panier.quantite}}
                    </td>
                </tr>
                {% if panier.quantite > 1 %}
                    <tr>
                        <td width="80%" style="text-align:left; padding: 0 2.5em; color: #000; padding-bottom: 20px">
                            Prix unitaire: {{panier.prix}}€
                        </td>
                    </tr>
                {% endif %}
            {% endfor %}
            <tr>
                <td width="80%" style="text-align:left; padding: 0 2.5em; color: #000; padding-bottom: 20px; border-top: 3px solid black; font-weight:bold;">
                    Total à regler:
                </td>
                <td width="20%" style="text-align:right; padding: 0 2.5em; color: #000; padding-bottom: 20px; border-top: 3px solid black; font-weight:bold;">
                    {{total}}€
                </td>
            </tr>
        </table>
    </div>
   
</div>

templates/commande/index.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Commande{% endblock %}

{% block body %}
{{form(form)}}
{% endblock %}

templates/commande/view.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Détail de ma commande{% endblock %}

{% block body %}
<style>
    tr{
        border: 1px solid black;
    }
    td{
        font-weight: bold;
        text-align: center;
        color: white;
    }
    tr{
        margin: 10px;
    }
    h1{
        color: white;
    }
</style>


<h1>Vous avez commandé:</h1>
<table>
    <thead>
        <th>Produit</th>
        <th>Quantité</th>
        <th>Prix</th>
    </thead>
    {% for ligne in commande.ligneCommandes %}
        <tr>
            <td>{{ligne.produit.nom}}</td>
            <td>{{ligne.quantite}}</td>
            <td>{{ligne.prix}}€</td>
        </tr>
    {% endfor %}
</table>

{% endblock %}